# Generated by Django 4.1.7 on 2023-04-18 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_publis',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
