# Generated by Django 4.1.7 on 2023-04-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_image_img_publis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descriptions',
            field=models.CharField(max_length=300),
        ),
    ]
