# Generated by Django 4.1.7 on 2023-04-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descriptions',
            field=models.TextField(),
        ),
    ]
